<div class="homepage">
    <!-- <h1>Home Page Template</h1> -->

    <section class="hero-image">
        <?php // references the cms block with the specified id
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('salt_life_hero')
        ->toHtml();
        ?>

        <article class="hero-caption">
            <?php // references the cms block with the specified id
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('salt_life_hero_caption')
            ->toHtml();
            ?>
        </article>
    </section>

    <section class="home-content">

        <article class="kicker mens-kicker">
            <a class="kicker-link" href="men.html">
                <?php // references the cms block with the specified id
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('salt_life_mens_kicker')
                ->toHtml();
                ?>
                <h2>MENS</h2><span> SHOP ALL</span>
            </a>
    
            <?php 
            echo $this->getLayout()
            ->createBlock("Magento\Catalog\Block\Product\Widget\NewWidget")
            ->setDisplayType("all_products")
            ->setProductsCount("2")
            ->setTemplate("product/widget/new/content/new_grid.phtml")->toHtml()
            ?>
    
        </article>
    
        <article class="kicker ladies-kicker">
            <?php 
            echo $this->getLayout()
            ->createBlock("Magento\Catalog\Block\Product\Widget\NewWidget")
            ->setDisplayType("all_products")
            ->setProductsCount("2")
            ->setTemplate("product/widget/new/content/new_grid.phtml")->toHtml()
            ?>

            <a class="kicker-link" href="women.html">
                <?php // references the cms block with the specified id
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('salt_life_ladies_kicker')
                ->toHtml();
                ?>
                <h2>LADIES</h2><span> SHOP ALL</span>
            </a>
    
        </article>
    
        <article class="kicker gear-kicker">
            <a href="">

                <?php // references the cms block with the specified id
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('salt_life_gear_kicker')
                ->toHtml();
                ?>
            </a>

            
            <div class="kicker-text">
                <h2>GEAR</h2><span> SHOP ALL</span>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum, voluptas!</p>
                <a href=""><span>></span> DECALS</a>
                <a href=""><span>></span> ACCESSORIES</a>
                <a href=""><span>></span> HOME & OUTDOORS</a>
            </div>

            <?php // references the cms block with the specified id
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('salt_life_gear_kicker_foreground')
            ->toHtml();
            ?>
        </article>

        <article class="featured-category">
            <?php // references the cms block with the specified id
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('salt_life_featured_cat')
            ->toHtml();
            ?>
        </article>

        <article class="explore">
            <a href="">
                <?php // references the cms block with the specified id
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('salt_life_explore1')
                ->toHtml();
                ?>
                <h5><span>></span> SALT LIFE GIVES BACK</h5>
            </a>
            <a href="">
                <?php // references the cms block with the specified id
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('salt_life_explore2')
                ->toHtml();
                ?>
                <h5><span>></span> EAT HERE</h5>
            </a>
            <a href="">
                <?php // references the cms block with the specified id
                echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('salt_life_explore3')
                ->toHtml();
                ?>
                <h5><span>></span> TEAM SALT LIFE</h5>
            </a>
        </article>

        <article class="adventure">
            <h2>SHARE YOUR <span>#SALTLIFE</span> ADVENTURES</h2>
            <?php // references the cms block with the specified id
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('salt_life_adventure1')
            ->toHtml();
            ?>

            <?php // references the cms block with the specified id
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('salt_life_adventure2')
            ->toHtml();
            ?>

            <?php // references the cms block with the specified id
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('salt_life_adventure3')
            ->toHtml();
            ?>

            <?php // references the cms block with the specified id
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('salt_life_adventure4')
            ->toHtml();
            ?>

            <?php // references the cms block with the specified id
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('salt_life_adventure5')
            ->toHtml();
            ?>

            <?php // references the cms block with the specified id
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('salt_life_adventure6')
            ->toHtml();
            ?>

        </article>


    </section>

</div>